import React from 'react';

export const THEMES = [
  { id: 'cyan', name: 'سماوي', primary: '#00f2ff', bg: '#02040a' },
  { id: 'gold', name: 'ذهبي', primary: '#ffd700', bg: '#0a0802' },
  { id: 'emerald', name: 'زمردي', primary: '#10b981', bg: '#020a06' },
  { id: 'rose', name: 'وردي', primary: '#f43f5e', bg: '#0a0204' },
  { id: 'violet', name: 'بنفسجي', primary: '#8b5cf6', bg: '#06020a' },
  { id: 'amber', name: 'كهرماني', primary: '#f59e0b', bg: '#0a0602' },
  { id: 'blue', name: 'أزرق', primary: '#3b82f6', bg: '#02040a' },
  { id: 'indigo', name: 'نيلي', primary: '#6366f1', bg: '#03030a' },
  { id: 'teal', name: 'تركواز', primary: '#14b8a6', bg: '#020a09' },
  { id: 'orange', name: 'برتقالي', primary: '#f97316', bg: '#0a0502' },
  // Add more to reach 30+ if needed, but let's start with these
  { id: 'crimson', name: 'قرمزي', primary: '#dc2626', bg: '#0a0202' },
  { id: 'lime', name: 'ليموني', primary: '#84cc16', bg: '#060a02' },
  { id: 'fuchsia', name: 'فوشيا', primary: '#d946ef', bg: '#0a0209' },
  { id: 'sky', name: 'سماء', primary: '#0ea5e9', bg: '#02060a' },
  { id: 'cyan-dark', name: 'سماوي غامق', primary: '#0891b2', bg: '#010506' },
  { id: 'emerald-dark', name: 'زمردي غامق', primary: '#059669', bg: '#010604' },
  { id: 'violet-dark', name: 'بنفسجي غامق', primary: '#7c3aed', bg: '#040106' },
  { id: 'rose-dark', name: 'وردي غامق', primary: '#e11d48', bg: '#060102' },
  { id: 'amber-dark', name: 'كهرماني غامق', primary: '#d97706', bg: '#060401' },
  { id: 'slate', name: 'رصاصي', primary: '#64748b', bg: '#0f172a' },
  { id: 'zinc', name: 'زنك', primary: '#71717a', bg: '#09090b' },
  { id: 'stone', name: 'حجري', primary: '#78716c', bg: '#0c0a09' },
  { id: 'red', name: 'أحمر', primary: '#ef4444', bg: '#0a0202' },
  { id: 'green', name: 'أخضر', primary: '#22c55e', bg: '#020a04' },
  { id: 'yellow', name: 'أصفر', primary: '#eab308', bg: '#0a0a02' },
  { id: 'purple', name: 'أرجواني', primary: '#a855f7', bg: '#0a020a' },
  { id: 'pink', name: 'زهري', primary: '#ec4899', bg: '#0a0206' },
  { id: 'cyan-light', name: 'سماوي فاتح', primary: '#22d3ee', bg: '#082f49' },
  { id: 'teal-light', name: 'تركواز فاتح', primary: '#2dd4bf', bg: '#042f2e' },
  { id: 'emerald-light', name: 'زمردي فاتح', primary: '#34d399', bg: '#064e3b' },
  { id: 'indigo-light', name: 'نيلي فاتح', primary: '#818cf8', bg: '#1e1b4b' },
];

export const AI_TOOLS = [
  { id: 1, name: 'ChatGPT History', desc: 'مساعد ذكي للبحث التاريخي', icon: 'MessageSquare', url: 'https://chat.openai.com' },
  { id: 2, name: 'Gemini AI', desc: 'تحليل الخرائط والجغرافيا بذكاء', icon: 'Sparkles', url: 'https://gemini.google.com' },
  { id: 3, name: 'Claude History', desc: 'كتابة مقالات تاريخية احترافية', icon: 'PenTool', url: 'https://claude.ai' },
  { id: 4, name: 'Perplexity', desc: 'البحث عن المصادر الموثوقة', icon: 'Search', url: 'https://www.perplexity.ai' },
  { id: 5, name: 'Google Earth', desc: 'استكشاف المواقع التاريخية 3D', icon: 'Globe', url: 'https://earth.google.com' },
  { id: 6, name: 'Midjourney History', desc: 'تخيل الأحداث التاريخية بصرياً', icon: 'Image', url: 'https://www.midjourney.com' },
  { id: 7, name: 'WolframAlpha', desc: 'بيانات وإحصائيات جغرافية دقيقة', icon: 'Calculator', url: 'https://www.wolframalpha.com' },
  { id: 8, name: 'DeepL Translator', desc: 'ترجمة المراجع التاريخية بدقة', icon: 'Languages', url: 'https://www.deepl.com' },
  { id: 9, name: 'Canva Education', desc: 'تصميم خرائط مفاهيمية رائعة', icon: 'Palette', url: 'https://www.canva.com' },
  { id: 10, name: 'Quizlet', desc: 'حفظ التواريخ والمصطلحات', icon: 'Brain', url: 'https://quizlet.com' },
  { id: 11, name: 'Khan Academy', desc: 'شروحات تاريخية عالمية', icon: 'GraduationCap', url: 'https://www.khanacademy.org' },
  { id: 12, name: 'National Geographic', desc: 'وثائقيات جغرافية وتاريخية', icon: 'Map', url: 'https://www.nationalgeographic.com' },
  { id: 13, name: 'Ancient History', desc: 'موسوعة التاريخ القديم', icon: 'Library', url: 'https://www.worldhistory.org' },
  { id: 14, name: 'Google Scholar', desc: 'أبحاث تاريخية أكاديمية', icon: 'BookOpen', url: 'https://scholar.google.com' },
  { id: 15, name: 'History.com', desc: 'أرشيف الأحداث التاريخية', icon: 'History', url: 'https://www.history.com' },
  { id: 16, name: 'Britannica', desc: 'الموسوعة البريطانية للتاريخ', icon: 'Book', url: 'https://www.britannica.com' },
  { id: 17, name: 'UNESCO Heritage', desc: 'مواقع التراث العالمي', icon: 'Landmark', url: 'https://whc.unesco.org' },
  { id: 18, name: 'Archive.org', desc: 'كتب ووثائق تاريخية نادرة', icon: 'Archive', url: 'https://archive.org' },
  { id: 19, name: 'Coursera History', desc: 'دورات تاريخية معتمدة', icon: 'Award', url: 'https://www.coursera.org' },
  { id: 20, name: 'YouTube Education', desc: 'دروس مرئية في التاريخ والجغرافيا', icon: 'Play', url: 'https://www.youtube.com' },
];
